name: Deploy to Huggingface Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add remote
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://zuhair96:$HFhuggingface.co/spaces/zuhair96/Prophet-Forecasting

      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://zuhair96:$HFhuggingface.co/spaces/zuhair96/Prophet-Forecasting
        